# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '* */12 */10 * *'
  push:
    branches:
      - '!main'
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Allow Scripts to run
        run: chmod +x createcidr.sh
      - name: Create CIDR Whitelist files
        run: ./createcidr.sh
      - name: push
        uses: actions-x/commit@v6
        with:
            email: me@example.com
            name: ChillBill Actions AutoCommit
            branch: main
            files: '*.cidr'
#            token: ${{ secrets.edlwl_token }}
            force: true
