# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 */6 1-31/2 * *'
  push:
    branches:
      - main
#      - '!**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install some supporting files
        run: apt-get install whois
      - name: Allow Scripts to run
        run: chmod +x *.sh
      - name: Create CIDR Whitelist files (Original)
        run: ./createcidr.sh
      - name: Create CIDR Whitelist files (Using the ASN)
        run: ./createcidr.asn.sh
      - name: Commit and push the file
        uses: maxgfr/github-commit-push-file@main
        with:
          commit_name: 'FIX: Updated CIDR files.'
